fix: Remove VoiceClient from DJSClient when destroyed
kijk2869/discodo.js pull request #8
Opened 2021-05-13 01:00 UTC by despenser08

This PR fixes error `404: VoiceClient not found` & AudioSource typings.

2021-05-13 01:34 UTC, kijk2869 requested changes

2021-05-13 01:34 UTC, kijk2869 commented on src/DJSClient.js
> +        this.voiceClients.delete(`${guild_id}`)
https://github.com/kijk2869/discodo.js/blob/edcf59b5d5719f6c3a43a19d4169254f92fb0fb4/src/voiceClient.js#L72

2021-05-13 01:39 UTC, despenser08 commented
Why `destroy()` method used in example?
https://github.com/kijk2869/discodo.js/blob/edcf59b5d5719f6c3a43a19d4169254f92fb0fb4/example/basic.js#L47

2021-05-13 04:59 UTC, kijk2869 commented
> Why `destroy()` method used in example?
> https://github.com/kijk2869/discodo.js/blob/edcf59b5d5719f6c3a43a19d4169254f92fb0fb4/example/basic.js#L47

Discodo.js asks the server to destroy the voice client by `VC.destroy()`

After destroying the voice client, the server sends `VC_DESTROYED` event.

When discodo.js receives `VC_DESTROYED`, it calls `VC.stop()` internally.

2021-05-14 02:50 UTC, kijk2869 approved these changes

2021-05-14 02:50 UTC, merged